In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import copy
import warnings
from IPython.display import display
%matplotlib inline

In [76]:
meta_df = pd.read_csv('data/big/ACS_16_5YR_B02001_metadata.csv',
                      encoding='ISO-8859-1', header=None)
df = pd.read_csv('data/big/ACS_16_5YR_B02001_with_ann.csv', encoding='ISO-8859-1', 
                 header=0, skiprows=[0], names=meta_df[1])
df['Id'] = df['Id'].str.slice(-5)
df.head(5)

,Id,Id2,Geography,Estimate; Total:,Margin of Error; Total:,Estimate; Total: - White alone,Margin of Error; Total: - White alone,Estimate; Total: - Black or African American alone,Margin of Error; Total: - Black or African American alone,Estimate; Total: - American Indian and Alaska Native alone,...,Estimate; Total: - Native Hawaiian and Other Pacific Islander alone,Margin of Error; Total: - Native Hawaiian and Other Pacific Islander alone,Estimate; Total: - Some other race alone,Margin of Error; Total: - Some other race alone,Estimate; Total: - Two or more races:,Margin of Error; Total: - Two or more races:,Estimate; Total: - Two or more races: - Two races including Some other race,Margin of Error; Total: - Two or more races: - Two races including Some other race,"Estimate; Total: - Two or more races: - Two races excluding Some other race, and three or more races","Margin of Error; Total: - Two or more races: - Two races excluding Some other race, and three or more races"
0,01001,1001,"Autauga County, Alabama",55049,*****,42311,336,10196,260,226,...,31,33,764,381,1077,324,70,72,1007,320
1,01003,1003,"Baldwin County, Alabama",199510,*****,172441,618,18594,635,1355,...,0,27,1766,587,4016,758,908,477,3108,692
2,01005,1005,"Barbour County, Alabama",26614,*****,12430,202,12756,71,46,...,0,21,1099,203,154,67,6,10,148,67
3,01007,1007,"Bibb County, Alabama",22572,*****,17370,15,4788,216,81,...,0,21,8,15,311,214,0,21,311,214
4,01009,1009,"Blount County, Alabama",57704,*****,55073,284,905,97,201,...,0,27,501,254,932,196,28,27,904,189

In [77]:
tmp = [x.startswith('Margin') for x in df.columns]
df.drop(df.columns[tmp], axis=1, inplace=True)
df.drop(['Id2'], axis=1, inplace=True)

In [78]:
df.head(5)

,Id,Geography,Estimate; Total:,Estimate; Total: - White alone,Estimate; Total: - Black or African American alone,Estimate; Total: - American Indian and Alaska Native alone,Estimate; Total: - Asian alone,Estimate; Total: - Native Hawaiian and Other Pacific Islander alone,Estimate; Total: - Some other race alone,Estimate; Total: - Two or more races:,Estimate; Total: - Two or more races: - Two races including Some other race,"Estimate; Total: - Two or more races: - Two races excluding Some other race, and three or more races"
0,01001,"Autauga County, Alabama",55049,42311,10196,226,444,31,764,1077,70,1007
1,01003,"Baldwin County, Alabama",199510,172441,18594,1355,1338,0,1766,4016,908,3108
2,01005,"Barbour County, Alabama",26614,12430,12756,46,129,0,1099,154,6,148
3,01007,"Bibb County, Alabama",22572,17370,4788,81,14,0,8,311,0,311
4,01009,"Blount County, Alabama",57704,55073,905,201,92,0,501,932,28,904

In [79]:
df.columns = [x.replace('Estimate; Total: - ','') for x in df.columns]
df.columns = [x.replace(':','') for x in df.columns]
df.columns = [x.replace(';','') for x in df.columns]
df.columns = [x.replace(' ','_') for x in df.columns]
df.head(5)

,Id,Geography,Estimate_Total,White_alone,Black_or_African_American_alone,American_Indian_and_Alaska_Native_alone,Asian_alone,Native_Hawaiian_and_Other_Pacific_Islander_alone,Some_other_race_alone,Two_or_more_races,Two_or_more_races_-_Two_races_including_Some_other_race,"Two_or_more_races_-_Two_races_excluding_Some_other_race,_and_three_or_more_races"
0,01001,"Autauga County, Alabama",55049,42311,10196,226,444,31,764,1077,70,1007
1,01003,"Baldwin County, Alabama",199510,172441,18594,1355,1338,0,1766,4016,908,3108
2,01005,"Barbour County, Alabama",26614,12430,12756,46,129,0,1099,154,6,148
3,01007,"Bibb County, Alabama",22572,17370,4788,81,14,0,8,311,0,311
4,01009,"Blount County, Alabama",57704,55073,905,201,92,0,501,932,28,904

In [87]:
# df['Id'] = df['Id'].str.slice(-5)
for col in df.columns[3:]:
    df[col] = df[col] / df['Estimate_Total']

In [88]:
df.to_csv('data/ACS_16_pop_demos.csv', index=False)

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3142 entries, 0 to 3141
Data columns (total 12 columns):
Id                                                                                  3142 non-null object
Geography                                                                           3142 non-null object
Estimate_Total                                                                      3142 non-null int64
White_alone                                                                         3142 non-null float64
Black_or_African_American_alone                                                     3142 non-null float64
American_Indian_and_Alaska_Native_alone                                             3142 non-null float64
Asian_alone                                                                         3142 non-null float64
Native_Hawaiian_and_Other_Pacific_Islander_alone                                    3142 non-null float64
Some_other_race_alone                                                               3142 non-null float64
Two_or_more_races                                                                   3142 non-null float64
Two_or_more_races_-_Two_races_including_Some_other_race                             3142 non-null float64
Two_or_more_races_-_Two_races_excluding_Some_other_race,_and_three_or_more_races    3142 non-null float64
dtypes: float64(9), int64(1), object(2)
memory usage: 294.6+ KB

In [95]:
tmp = df.columns
len(tmp)
for val in tmp[-10:]:
    print('<option value="{0}">{0}</option>'.format(val))

<option value="Estimate_Total">Estimate_Total</option>
<option value="White_alone">White_alone</option>
<option value="Black_or_African_American_alone">Black_or_African_American_alone</option>
<option value="American_Indian_and_Alaska_Native_alone">American_Indian_and_Alaska_Native_alone</option>
<option value="Asian_alone">Asian_alone</option>
<option value="Native_Hawaiian_and_Other_Pacific_Islander_alone">Native_Hawaiian_and_Other_Pacific_Islander_alone</option>
<option value="Some_other_race_alone">Some_other_race_alone</option>
<option value="Two_or_more_races">Two_or_more_races</option>
<option value="Two_or_more_races_-_Two_races_including_Some_other_race">Two_or_more_races_-_Two_races_including_Some_other_race</option>
<option value="Two_or_more_races_-_Two_races_excluding_Some_other_race,_and_three_or_more_races">Two_or_more_races_-_Two_races_excluding_Some_other_race,_and_three_or_more_races</option>